# Generated by Django 4.2.3 on 2023-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pupil'),
        ),
    ]
